[package]
name = "mdbook-docslab"
description = "mdBook preprocessor for interactive code with docslab"
repository = "https://github.com/rerobots/docslab"
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
mdbook = "0.4.37"
